#!/bin/bash

VALUE_MAKE=BMW
TXT_ENGINE_PERFORMANCE=120
TXT_DATE_MANUFACTURE=12/01/2020
VALUE_NUMBER_SEATS='2'
VALUE_FUEL_TYPE=Diesel
TXT_PAYLOAD=120
TXT_TOTAL_WEIGHT=120
TXT_LIST_PRICE=500
TXT_ANNUAL_MILEAGE=120

TXT_FIRST_NAME=Rennan
TXT_LAST_NAME=Gimenez
TXT_BIRTH_DATE=07/29/1999
VALUE_COUNTRY=Brazil
TXT_ZIP_CODE=13187149
VALUE_OCCUPATION=Employee

TXT_START_DATE=12/01/2021
VALUE_INSURANCE_SUM=3000000
VALUE_MERIT_RATING='Super Bonus'
VALUE_DAMAGE_INSURANCE='Full Coverage'
VALUE_COURTESY_CAR=Yes

TXT_EMAIL=contato.rennang@gmail.com
TXT_USERNAME=rennanG
TXT_PASSWORD=Inicial@2021

robot -d '..\results\' -t 'Case 1: Fill forms and send quote' -v VALUE_MAKE:$VALUE_MAKE -v VALUE_MODEL:$VALUE_MODEL -v TXT_CYLINDER_CAPACITY:$TXT_CYLINDER_CAPACITY -v TXT_ENGINE_PERFORMANCE:$TXT_ENGINE_PERFORMANCE -v TXT_DATE_MANUFACTURE:$TXT_DATE_MANUFACTURE -v VALUE_NUMBER_SEATS:"$VALUE_NUMBER_SEATS" -v VALUE_FUEL_TYPE:$VALUE_FUEL_TYPE -v TXT_PAYLOAD:$TXT_PAYLOAD -v TXT_TOTAL_WEIGHT:$TXT_TOTAL_WEIGHT -v TXT_LIST_PRICE:$TXT_LIST_PRICE -v TXT_ANNUAL_MILEAGE:$TXT_ANNUAL_MILEAGE -v TXT_FIRST_NAME:$TXT_FIRST_NAME -v TXT_LAST_NAME:$TXT_LAST_NAME -v TXT_BIRTH_DATE:$TXT_BIRTH_DATE -v VALUE_COUNTRY:$VALUE_COUNTRY -v TXT_ZIP_CODE:$TXT_ZIP_CODE -v VALUE_OCCUPATION:$VALUE_OCCUPATION -v TXT_START_DATE:$TXT_START_DATE -v VALUE_INSURANCE_SUM:$VALUE_INSURANCE_SUM -v VALUE_MERIT_RATING:"$VALUE_MERIT_RATING" -v VALUE_DAMAGE_INSURANCE:"$VALUE_DAMAGE_INSURANCE" -v VALUE_COURTESY_CAR:$VALUE_COURTESY_CAR -v TXT_EMAIL:$TXT_EMAIL -v TXT_USERNAME:$TXT_USERNAME -v TXT_PASSWORD:$TXT_PASSWORD '..\tests\tests.robot'